---
version: "2"

services:
  mongo:
    image: mongo:3.4
    ports:
      - "27017:27017"

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      BIND: ":80"
      MONGO_DB_URL: "mongodb://mongo:27017"
    ports:
      - "8080:80"
