---
version: "2"

services:
  mongo:
    image: mongo:3.4

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      BIND: ":80"
      MONGO: "mongodb://mongo:27017"
    ports:
      - "8080:80"
